#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE_DEFAULT="${STAGE_DIR}/bakery.env"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --env-file <path>     Env file to source (default: stages/12-k8s-image-bakery/bakery.env)
  --output <path>       Output yaml path (default: ./helm-values.overrides.yaml)
  -h, --help            Show this help
USAGE
}

ENV_FILE="${ENV_FILE_DEFAULT}"
OUTPUT_FILE="${STAGE_DIR}/helm-values.overrides.yaml"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

REGISTRY="${REGISTRY:-localhost}"
REGISTRY_NAMESPACE="${REGISTRY_NAMESPACE:-alfresco}"
TAG="${TAG:-25.3.0-custom}"
IMAGE_PREFIX="${REGISTRY}/${REGISTRY_NAMESPACE}"

cat > "${OUTPUT_FILE}" <<YAML
# Generated by render-helm-overrides.sh
# For chart: helm/alfresco-content-services (acs-deployment)

alfresco-repository:
  image:
    repository: ${IMAGE_PREFIX}/alfresco-content-repository
    tag: ${TAG}

share:
  image:
    repository: ${IMAGE_PREFIX}/alfresco-share
    tag: ${TAG}

alfresco-search-enterprise:
  liveIndexing:
    mediation:
      image:
        repository: ${IMAGE_PREFIX}/alfresco-elasticsearch-live-indexing-mediation
        tag: ${TAG}
    metadata:
      image:
        repository: ${IMAGE_PREFIX}/alfresco-elasticsearch-live-indexing-metadata
        tag: ${TAG}
    path:
      image:
        repository: ${IMAGE_PREFIX}/alfresco-elasticsearch-live-indexing-path
        tag: ${TAG}
    content:
      image:
        repository: ${IMAGE_PREFIX}/alfresco-elasticsearch-live-indexing-content
        tag: ${TAG}
  reindexing:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-elasticsearch-reindexing
      tag: ${TAG}

alfresco-transform-service:
  transformrouter:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-transform-router
      tag: ${TAG}
  filestore:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-shared-file-store
      tag: ${TAG}
  pdfrenderer:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-pdf-renderer
      tag: ${TAG}
  imagemagick:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-imagemagick
      tag: ${TAG}
  libreoffice:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-libreoffice
      tag: ${TAG}
  tika:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-tika
      tag: ${TAG}
  transformmisc:
    image:
      repository: ${IMAGE_PREFIX}/alfresco-transform-misc
      tag: ${TAG}

alfresco-sync-service:
  image:
    repository: ${IMAGE_PREFIX}/alfresco-sync-service
    tag: ${TAG}

alfresco-digital-workspace:
  image:
    repository: ${IMAGE_PREFIX}/alfresco-digital-workspace
    tag: ${TAG}
YAML

echo "Wrote ${OUTPUT_FILE}"
